input_images: ./images
seed: 1337
resolution: 512
train_batch_size: 4
num_train_epochs: 4000
max_train_steps: 1000
is_lora: true
unet_learning_rate: 1e-6
ti_lr: 3e-4
lora_lr: 1e-4
lr_scheduler: constant
lr_warmup_steps: 100
token_string: TOK
caption_prefix: "a photo of TOK"
mask_target_prompts: null
crop_based_on_salience: true
use_face_detection_instead: false
clipseg_temperature: 1.0
verbose: true
checkpointing_steps: 200
output_dir: ./sdxl-finetuned
